name: replace-comment-html
description: This action upserts HTML in GitHub issue or pull request comments using CSS selectors
author: Hunter Tunnicliff
runs:
  using: node20
  main: lib/index.js
inputs:
  token:
    description: GitHub token
    required: true
  html:
    description: HTML to create or update
    required: true
  selector:
    description: A CSS selector for identifying the element to update
    required: true
  parent-selector:
    description: A CSS selector for identfying a parent to append the element to
    required: false
  mode:
    description: "Which strategy to use for modifying comments: upsert (default), create-only"
    required: false
    default: upsert
outputs:
  comment-id:
    description: The ID of the comment that was created or updated
branding:
  icon: file-text
  color: gray-dark
